apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
    name: egress-gateway
    namespace: kube-pconline
spec:
    selector:
        app: egress-gateway
    servers:
        - port:
            number: 90
            name: http
            protocol: HTTP
          hosts:
            - 219.136.244.122
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: test-passpord
  namespace: kube-pconline
spec:
  hosts:
    - "recognize.pconline.com.cn"
  address: 219.136.244.122
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-passpord
  namespace: kube-pconline
spec:
  hosts:
    - "219.136.244.122"
  http:
    - headers:
        request:
          add:
            host: recognize.pconline.com.cn
      match:
        - sourceLabels:
            app: nginx-light-video-deployment
      route:
        - destination:
            host: test-passpord.kube-pconline.svc.cluster.local