apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-passpord
  namespace: kube-pconline
spec:
  hosts:
    - "219.136.244.122"
  http:
    - headers:
      request:
        add:
          host: recognize.pconline.com.cn
    - match:
        - sourceLabels:
            app: nginx-light-video-deployment
      route:
        - destination:
            host: "recognize.pconline.com.cn"
