apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  labels:
    account: my-service-account-account
---
apiVersion: v1
kind: Pod
metadata:
  name: my-service-account-service
  namespace: default
  labels:
    name: my-service-account-name
    tier: my-service-account-tier
spec:
  containers:
    - name: my-service-account-app
      image: hello-world
      ports:
        - name: http
          containerPort: 80
  serviceAccountName: my-service-account
