apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: demo-deployment
  ports:
    - port: 8127
      # 对这个地方的TCP协议表示怀疑
      protocol: TCP
      targetPort: 8127
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-deployment
  name: demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-deployment
  template:
    metadata:
      labels:
        app: demo-deployment
    spec:
      containers:
        - image: demo:latest
          imagePullPolicy: IfNotPresent
          name: demo
          ports:
            - containerPort: 8127
              protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: demo-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - mytoys.fun
      port:
        name: entry-port
        number: 80
        protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-virtual-service
spec:
  gateways:
    - demo-gateway
    - mesh
  hosts:
    - demo-service.default.svc.cluster.local
    - mytoys.fun
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: demo-service.default.svc.cluster.local
            port:
              number: 8127
